name: ecs-fargate-deployment

on:
  pull_request:
    branches: [ main ]
    paths: [ 'infra/**', 'src/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      TERRAFORM_PATH: infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # This makes it easier to capture outputs

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init

      - name: Terraform Apply (Infrastructure First)
        id: apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply -var-file="terraform.tfvars" -auto-approve -no-color

      - name: Build and Push Docker Image
        run: |
          # 1. Capture the Registry URL from the Login step
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          
          # 2. Extract the REPO_NAME directly from Terraform Output
          cd ${{ env.TERRAFORM_PATH }}
          REPOSITORY=$(terraform output -raw ecr_repository_name)
          cd ..
          
          IMAGE_TAG=latest
          
          echo "Targeting ECR Repo: $REPOSITORY"
          
          # 3. Build using the 'src' folder as context
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./src
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy Application (ECS Force Update)
        run: |
          # 4. Extract Cluster and Service names from Terraform Output
          cd ${{ env.TERRAFORM_PATH }}
          CLUSTER=$(terraform output -raw ecs_cluster_name)
          SERVICE=$(terraform output -raw ecs_service_name)
          cd ..
          
          echo "Updating Service $SERVICE in Cluster $CLUSTER"
          
          aws ecs update-service \
            --cluster $CLUSTER \
            --service $SERVICE \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}

      - name: Wait for Service Stability
        run: |
          cd ${{ env.TERRAFORM_PATH }}
          CLUSTER=$(terraform output -raw ecs_cluster_name)
          SERVICE=$(terraform output -raw ecs_service_name)
          cd ..
          
          echo "Waiting for health checks to pass..."
          aws ecs wait services-stable \
            --cluster $CLUSTER \
            --services $SERVICE \
            --region ${{ env.AWS_REGION }}
          echo "âœ… Deployment Successful!"
