name: on-pr-main-day6

on:
  pull_request:
    branches: [ main ]
    paths: [ 'infra/**', 'src/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      TERRAFORM_VER: 1.8.1
      TERRAFORM_PATH: infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.registry }}
          # Ensure this matches your actual ECR name in AWS
          ECR_REPOSITORY: student-portal-repo 
          IMAGE_TAG: latest
        run: |
          # The context is './src' because that is where your Dockerfile lives
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply -var-file="terraform.tfvars" -auto-approve -no-color

      - name: Deploy Application (ECS Update)
        run: |
          aws ecs update-service \
            --cluster dev-student-portal-cluster \
            --service dev-student-portal-service \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}

      - name: Wait for Service Stability
        run: |
          echo "Waiting for ALB health checks to pass on /login..."
          aws ecs wait services-stable \
            --cluster dev-student-portal-cluster \
            --services dev-student-portal-service \
            --region ${{ env.AWS_REGION }}

